### PR TITLE
Create simple EKS & deploying s3 controller on top of it

### PR DESCRIPTION
**Pull request by pkprzekwas**

### CODE REVIEW

**Comment by pkprzekwas** [comment]
Ran Plan for dir: `infra/aws/terraform/ack-playground` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis-data/bin/terraform1.3.9 init -input=false -upgrade" in "/atlantis-data/repos/pkprzekwas/k8s.io/1/default/infra/aws/terraform/ack-playground": exit status 1
Upgrading modules...
Downloading registry.terraform.io/terraform-aws-modules/eks/aws 19.10.0 for eks...
- eks in .terraform/modules/eks
- eks.eks_managed_node_group in .terraform/modules/eks/modules/eks-managed-node-group
- eks.eks_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
- eks.fargate_profile in .terraform/modules/eks/modules/fargate-profile
Downloading registry.terraform.io/terraform-aws-modules/kms/aws 1.1.0 for eks.kms...
- eks.kms in .terraform/modules/eks.kms
- eks.self_managed_node_group in .terraform/modules/eks/modules/self-managed-node-group
- eks.self_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
Downloading registry.terraform.io/terraform-aws-modules/iam/aws 5.11.2 for iam_eks_role...
- iam_eks_role in .terraform/modules/iam_eks_role/modules/iam-role-for-service-accounts-eks
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 3.19.0 for vpc...
- vpc in .terraform/modules/vpc

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: CZHX9BMF6FGAC37A, host id: GpeeiaBCb8nEjNY3ZCHehE9aFhQUyQrSe6t3AGDEx/EWaEXfkHgTFCHjITzerN6VTzWRFdy46xs=

```
</details>

**Comment by pkprzekwas** [comment]
atlantis

**Comment by pkprzekwas** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by patprzek** [comment]
atlantis

**Comment by pkprzekwas** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by patprzek** [comment]
atlantis plan

**Comment by pkprzekwas** [comment]
Ran Plan for dir: `infra/aws/terraform/ack-playground` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis-data/bin/terraform1.3.9 init -input=false -upgrade" in "/atlantis-data/repos/pkprzekwas/k8s.io/1/default/infra/aws/terraform/ack-playground": exit status 1
Upgrading modules...
Downloading registry.terraform.io/terraform-aws-modules/eks/aws 19.10.0 for eks...
- eks in .terraform/modules/eks
- eks.eks_managed_node_group in .terraform/modules/eks/modules/eks-managed-node-group
- eks.eks_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
- eks.fargate_profile in .terraform/modules/eks/modules/fargate-profile
Downloading registry.terraform.io/terraform-aws-modules/kms/aws 1.1.0 for eks.kms...
- eks.kms in .terraform/modules/eks.kms
- eks.self_managed_node_group in .terraform/modules/eks/modules/self-managed-node-group
- eks.self_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
Downloading registry.terraform.io/terraform-aws-modules/iam/aws 5.11.2 for iam_eks_role...
- iam_eks_role in .terraform/modules/iam_eks_role/modules/iam-role-for-service-accounts-eks
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 3.19.0 for vpc...
- vpc in .terraform/modules/vpc

Initializing the backend...
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: PA46BC18706QQAMF, host id: cbD5KA854vIiCwXF2VKR3/u8Uwomn+HOFOVY32dQ2BtZpDtmygL/7KEVYHKOULF6XW/BZmM8wtw=

```
</details>

**Pull request closed without merging**
